### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by codejnki** [MindscapeHQ/druid4net#11]
I'm looking at the DruidClient and Requestor classes and trying to figure out how to support basic authentication on a request.  Do you have any recommendations?

**Comment by j5alive** [comment]
I have two ideas about how to support this. 
1. Extract the Requester class into an interface and allow the user to implement and supply their own Requester. With this option you have complete control over how requests/responses are handled.
2. Add more options to the DruidClient to configure things like basic authentication or proxy settings. Probably introduce a Configuration class to set these and other configuration settings.

I might have a go at adding both of these options this weekend, if you can wait, then I'll get something up on Nuget too (along with a few other branches I had running for other additions to the client)

**Comment by codejnki** [comment]
I like that idea. I will keep watch and can provide feedback as soon as something is available.

**Comment by j5alive** [comment]
I've created a PR https://github.com/MindscapeHQ/druid4net/pull/12 for this now. Take a look and let me know if it suits your needs. I still need to do some testing on it and write some unit tests.

**Comment by j5alive** [comment]
Version 2.0.1 is released now with these changes. https://www.nuget.org/packages/Druid4Net/2.0.1
