### ISSUE TITLE
Optional Limit and Offset in DefaultLimitSpec

### ISSUE THREAD

**Issue by WolnyDominik** [MindscapeHQ/druid4net#35]
According to Druid documentation ([Limit Spec](https://druid.apache.org/docs/latest/querying/limitspec.html)) in `DefaultLimitSpec` `Limit` and `Offset` fields are optional integers and in current implementation both values are of type `int`. Is there any reason for this and is it possible to change them to `long?` or at least `int?`? Or is there some walkaround for sorting in GroupBy query without setting offset and limit?

**Comment by j5alive** [comment]
It seems like this has changed in 0.20, at least by looking at older versions of the documentation. We are open to PRs if you want to submit one that changes this behavior. As a work around, you could set offset to zero and limit to `int.MaxValue` (or some other really large number).
