### ISSUE TITLE
Not setting `Context:useCache` causes an UnderflowError

### ISSUE THREAD

**Issue by TomBonnerAtDerivitec** [MindscapeHQ/druid4net#42]
This might be the wrong repo almost so I'll try to flesh this out later, but the gist is that a seeming fresh instance of Druid if called with an empty context object will throw an error called JavaUnderflowException.

Given we set `useCache` to null this occurs on some calls. Oddly the error seems to have vanished now I made a single request with the useCache value set.

**Comment by QuantumNightmare** [comment]
Apologies for the late response - This repo is a .NET Druid client. It sounds like you're using a Java client such as this: https://github.com/zapr-oss/druidry

**Comment by TomBonnerAtDerivitec** [comment]
For context. by wrong repo I meant I might have found an issue with Druid itself rather than the .NET Client.
